name: Deploy ON Push

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #Install NodeJS
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      
      #Install DepenDencies
      - name: Install dependencies
        run: npm install
      #Run Build
      - name: Build
        run: npm run build
        
      - name: HealthCheck
        run: echo "Health Check Passed"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./out
          name: nextjs-app
  deploy:
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name : Deploy To GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
